# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'UL Today' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # Pods for UL Today
   pod 'AFNetworking', '~> 3.0'
end
